### ISSUE TITLE
Is this thing pretty?

### ISSUE THREAD

**Issue by phationmationion** [phationmationion/redux-regeneration#1]
@gaearon, @markerikson, @timdorr: hi there!

I write to you because you have a deep relations with such an awesome instrument as Redux. Thanks for all your work: it's a great inspiration.

I have wrote syntax-sugar for Redux and here its repo. I have not put that code in npm: it's not a library for now, just a suggestion. I'm not sure that all is good here and hope that you can help me.

With that thing code of reducers becomes cleaner. But time of their reaction to an action can increase about 3 times for large apps with deep `state` (see benchmark in [test branch](https://github.com/phationmationion/redux-regeneration/tree/test)).

How do you think, can 3x-decrease of reducers speed be a problem? Or may concept of *regenerable state* be a bad thing itself for Redux? Or may be that functionality was implented before?

Will be great to have any comments from you!

**PS:** I'm not familiar with github communications and don't know what I really should do. Hope you will receive this message :)

Run demo at `localhost:3000`:

```
git clone https://github.com/phationmationion/redux-regeneration.git
cd redux-regeneration
npm i
npm start
```

**Comment by Smike16** [comment]
Hmmm, its an interesting solution. So much boilerplate, that we used to, is under the hood

**Comment by phationmationion** [comment]
@Smike16 yes, it cuts the code and can be used in so many cases. But it also makes reducers slower. Moreover, `regenerationMap` is not such clear as `nextState`. These points could be problematic in large scale. My main fear is bonded with it.

**Comment by markerikson** [comment]
It seems potentially useful.  Reducers are generally not the slowest part of an application to start with, so "3x slower" is not necessarily a big problem.

I've already added this lib to [my list of Redux reducer utilities](https://github.com/markerikson/redux-ecosystem-links/blob/master/reducers.md).

**Comment by phationmationion** [comment]
@markerikson it's very good news: thanks!
